/**
 * freecards.js — the 300 cards free players get (20 per subject, spread over difficulty and question type).
 * Generated by tools/pick-free-cards.mjs. The list is fixed: do not edit by hand and do not regenerate after launch,
 * or cards would move in and out of the free set.
 */

export var FREE_CARD_IDS_BY_SUBJECT = {
  "Neurology": ["n021", "n022", "n023", "n030", "n031", "n032", "n033", "n034", "n050", "n051", "n052", "n053", "n054", "n100", "n103", "n104", "n162", "n163", "n169", "n180"
 ],
  "Cardiology": ["c100", "c101", "c107", "c108", "c109", "c120", "c121", "c122", "c123", "c124", "c125", "c126", "c127", "c128", "c129", "c138", "c139", "c150", "c155", "c169"
 ],
  "Nephrology": ["ne010", "ne013", "ne014", "ne015", "ne061", "ne062", "ne063", "ne066", "ne079", "ne100", "ne101", "ne102", "ne103", "ne104", "ne105", "ne106", "ne107", "ne108", "ne109", "ne118"
 ],
  "Psychiatry": ["p015", "p016", "p060", "p061", "p063", "p078", "p079", "p089", "p092", "p094", "p096", "p098", "p099", "p115", "p117", "p162", "p165", "p167", "p169", "p174"
 ],
  "Gastroenterology": ["g020", "g021", "g022", "g023", "g024", "g031", "g032", "g033", "g040", "g042", "g043", "g128", "g129", "g157", "g158", "g177", "g188", "g189", "g198", "g199"
 ],
  "Pulmonology": ["pu112", "pu114", "pu115", "pu117", "pu119", "pu160", "pu161", "pu162", "pu163", "pu164", "pu165", "pu166", "pu167", "pu169", "pu172", "pu173", "pu182", "pu195", "pu197", "pu199"
 ],
  "Infectious Disease": ["id001", "id002", "id075", "id077", "id084", "id088", "id089", "id098", "id099", "id110", "id118", "id119", "id129", "id142", "id148", "id158", "id159", "id169", "id170", "id197"
 ],
  "Endocrinology": ["en034", "en101", "en102", "en103", "en104", "en107", "en109", "en130", "en131", "en133", "en134", "en135", "en136", "en137", "en154", "en158", "en188", "en190", "en198", "en199"
 ],
  "Hematology/Oncology": ["he118", "he165", "he190", "he212", "he213", "he216", "he217", "he220", "he226", "he228", "he232", "he234", "he238", "he239", "he243", "he245", "he246", "he248", "he249", "he250"
 ],
  "Rheumatology": ["rh026", "rh032", "rh033", "rh036", "rh037", "rh043", "rh047", "rh050", "rh052", "rh087", "rh088", "rh089", "rh096", "rh097", "rh098", "rh102", "rh106", "rh121", "rh132", "rh145"
 ],
  "Obstetrics/Gynecology": ["ob066", "ob070", "ob121", "ob140", "ob141", "ob142", "ob143", "ob144", "ob145", "ob146", "ob147", "ob148", "ob149", "ob155", "ob156", "ob158", "ob162", "ob163", "ob169", "ob186"
 ],
  "Pediatrics": ["pe021", "pe022", "pe023", "pe024", "pe033", "pe040", "pe042", "pe043", "pe058", "pe059", "pe079", "pe088", "pe141", "pe142", "pe160", "pe161", "pe162", "pe181", "pe189", "pe200"
 ],
  "Surgery": ["su012", "su071", "su072", "su074", "su081", "su084", "su085", "su086", "su125", "su127", "su148", "su149", "su151", "su190", "su191", "su192", "su194", "su195", "su196", "su197"
 ],
  "Emergency Medicine": ["em004", "em007", "em014", "em018", "em019", "em061", "em063", "em069", "em077", "em091", "em092", "em093", "em094", "em095", "em096", "em098", "em142", "em172", "em175", "em179"
 ],
  "Multisystem / Mixed": ["mu030", "mu032", "mu033", "mu041", "mu042", "mu043", "mu045", "mu046", "mu050", "mu051", "mu052", "mu053", "mu054", "mu055", "mu060", "mu119", "mu141", "mu146", "mu147", "mu180"
 ]
};

export var FREE_CARD_IDS = new Set([].concat.apply([], Object.keys(FREE_CARD_IDS_BY_SUBJECT).map(function (k) { return FREE_CARD_IDS_BY_SUBJECT[k]; })));
